name: 'Close stale issues and PRs'

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@main
        with:
          repo-token: ${{ secrets.CI_GITHUB_TOKEN }}
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed in 7 days if no further activity occurs. Thank you
            for your contributions.
          stale-pr-message: >
            This pr has been automatically marked as stale because it has not had
            recent activity. It will be closed in 7 days if no further activity occurs. Thank you
            for your contributions.
          days-before-issue-stale: 30
          days-before-pr-stale: 30
          days-before-issue-close: 7
          days-before-pr-close: 7
          exempt-issue-labels: 'bug,help wanted,good first issue,dependencies'
          exempt-pr-labels: 'bug,help wanted,good first issue,dependencies'
          stale-issue-label: stale
          stale-pr-label: stale
